# Day 1: Python Basics for Data Science

Today’s Focus: Building a strong foundation with NumPy for handling data efficiently.

In [1]:
import numpy as np

# creating an array
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr, '\n')

# shape and size
print("Shape:", arr.shape)
print("Size:", arr.size)

# Reshape
reshaped = arr.reshape(3, 2)
print("Reshaped:\n", reshaped)

Array:
 [[1 2 3]
 [4 5 6]] 

Shape: (2, 3)
Size: 6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


In [2]:
# Mathematical Operations
# Basic operations
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

Sum: 21
Mean: 3.5
Standard Deviation: 1.707825127659933


In [3]:
# Dot product
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)
print("Dot Product:\n", result)

# Transpose
print("Transpose:\n", a.T)


Dot Product:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


In [4]:
np.random.seed(42)
X = np.random.rand(100, 3)  # 100 samples, 3 features
y = np.random.randint(0, 2, size=100)  # Binary labels (0 or 1)

print("Features:\n", X[:5])  # Display first 5 samples
print("Labels:\n", y[:5])

Features:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]
Labels:
 [0 1 1 1 0]
