In [1]:
import numpy as np

Assignment 1 Generate an np array of (a) vector of lenght 50 (b) two dimension of shape 5x4. Both uniformly distributed between 0 and 1 Split the two dimension array in 1 above into three arrays taking the first two rows, follow by the next two rows and put the remaining row in another variable Split the vector in 1 above into three arrays by taking the first 15, follow by the next 20 and the remaining into another variable. Create a 4x5 array: (a). Using manual method (b). Using randomly generated value between 0 and 1 (c). Using array of ones

Generate an np array of (a) vector of length 50 uniformly distributed between 0 and 1

In [2]:
vector = np.random.rand(50)
vector

array([0.62150824, 0.28304169, 0.12224934, 0.21570277, 0.47438687,
       0.47185698, 0.32967086, 0.5832257 , 0.7574852 , 0.55269416,
       0.86865326, 0.1793716 , 0.4292677 , 0.05275237, 0.85192012,
       0.91983031, 0.64860384, 0.57632823, 0.96227744, 0.42538378,
       0.39167557, 0.91711237, 0.78143455, 0.86339738, 0.28229575,
       0.78730083, 0.31612627, 0.56569004, 0.6855477 , 0.41579283,
       0.32797676, 0.68892302, 0.76175278, 0.77791813, 0.50010152,
       0.81053987, 0.21934388, 0.89092345, 0.85566247, 0.72353874,
       0.79695889, 0.89154447, 0.35879213, 0.28353568, 0.19554678,
       0.29405882, 0.41532967, 0.83775478, 0.89854429, 0.02382529])

# A 2 dimension array of shape 5 by 4 uniformly distributed between 0 and 1

In [3]:
dim_2_array = np.random.rand(5,4)
dim_2_array

array([[0.73982652, 0.5219696 , 0.25982114, 0.47946682],
       [0.37976196, 0.73614115, 0.70837939, 0.28739631],
       [0.68418954, 0.89201094, 0.34206431, 0.17584544],
       [0.04272606, 0.48313168, 0.5709098 , 0.93302089],
       [0.72435445, 0.4608028 , 0.42470505, 0.36663105]])

# Split the 2D array into three arrays

In [4]:
x1, x2, x3 = np.split(dim_2_array,(2,4))
# print(x1, x2, x3)
print('First two rows', x1, "\n")
print('Next two rows', x2 ,"\n")
print('Remaining rows', x3, "\n")

First two rows [[0.73982652 0.5219696  0.25982114 0.47946682]
 [0.37976196 0.73614115 0.70837939 0.28739631]] 

Next two rows [[0.68418954 0.89201094 0.34206431 0.17584544]
 [0.04272606 0.48313168 0.5709098  0.93302089]] 

Remaining rows [[0.72435445 0.4608028  0.42470505 0.36663105]] 



In [5]:
z1, z2, z3 = np.split(vector,(15,35))
# print(z1, z2,z3)
print('First 15', z1, "\n")
print('Next 20', z2 ,"\n")
print('Remaining rows', z3, "\n")

First 15 [0.62150824 0.28304169 0.12224934 0.21570277 0.47438687 0.47185698
 0.32967086 0.5832257  0.7574852  0.55269416 0.86865326 0.1793716
 0.4292677  0.05275237 0.85192012] 

Next 20 [0.91983031 0.64860384 0.57632823 0.96227744 0.42538378 0.39167557
 0.91711237 0.78143455 0.86339738 0.28229575 0.78730083 0.31612627
 0.56569004 0.6855477  0.41579283 0.32797676 0.68892302 0.76175278
 0.77791813 0.50010152] 

Remaining rows [0.81053987 0.21934388 0.89092345 0.85566247 0.72353874 0.79695889
 0.89154447 0.35879213 0.28353568 0.19554678 0.29405882 0.41532967
 0.83775478 0.89854429 0.02382529] 



# Create a 4x5 array: (a). Using manual method


In [6]:
dim = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
dim

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Create a 4x5 array:(b) Using randomly generated value

In [7]:
value = np.random.randint(0,2,(4,5))
value

array([[0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 1]])

Create a 4x5 array: (c). Using array of ones

In [8]:
arr_ones = np.ones([4,5])
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])